services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

  chat-ui:
    build:
      context: ./chat-ui
      dockerfile: Dockerfile
    container_name: chat-ui
    env_file:
      - .env
    environment:
      LLM_API_URL: http://anythingllm:3001
    ports:
      - "3000:3000"
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./chat-ui
          target: /app
        - action: rebuild
          path: ./chat-ui/package.json

  # llm-server:
  #   build:
  #     context: ./llm-server
  #     dockerfile: Dockerfile
  #   container_name: llm-server
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - anythingllm

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    cap_add:
      - SYS_ADMIN
    restart: always

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingllm
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./anythingllm/storage:/app/server/storage
      - ./anythingllm/.env:/app/server/.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - STORAGE_DIR=/app/server/storage
    restart: always
    depends_on:
      - ollama

volumes:
  postgres_data:
  ollama_data:
