from typing import Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    user_query: str
    use_query_processor: bool = False


class ChatResponse(BaseModel):
    semantic_query: str
    answer: str
    sources: list[str]
    tools_used: Optional[list[str]] = None


class LLMResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the LLM.")
    sources: list[str] = Field(description="List of source document identifiers.")


class AgentResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the LLM.")
    sources: list[str] = Field(description="List of source document identifiers.")
    tools_used: list[str] = Field(
        description="List of tool names used to generate the answer."
    )


# SQL RAG
class WhichTableResponse(BaseModel):
    table_names: list[str] = Field(description="The table names decided by the LLM.")


class SQLResponse(BaseModel):
    sql_query: str = Field(description="The sql query generated by the LLM.")


class FinalResponse(BaseModel):
    response: str = Field(description="The response generated by the LLM.")
