from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    user_query: str
    use_query_processor: bool = True  # Optional toggle


class ChatResponse(BaseModel):
    answer: str
    semantic_query: str
    sources: list[str]


class LLMResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the LLM.")
