services:

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama_playground
    ports:
      - "11500:11434"
    volumes:
      - ollama_data_playground:/root/.ollama
    cap_add:
      - SYS_ADMIN
  
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_playground
    ports:
      - "6334:6333"
    volumes:
      - qdrant_storage_playground:/qdrant/storage

volumes:
  ollama_data_playground:
  qdrant_storage_playground:
