from pydantic import BaseModel, Field


class CollectionDecisionResponse(BaseModel):
    collection: str = Field(description="The collection to search for the query.")
    # log: str = Field(description="Reasoning behinde llm's response.")


class RAGResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the LLM.")
    sources: list[str] = Field(description="List of source document identifiers.")
    # log: str = Field(description="Reasoning behinde llm's response.")


class SQLRAGResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the LLM.")
    sql: str = Field(description="The SQL query used to generate the answer.")
