from pydantic import BaseModel, Field


class CollectionDecisionResponse(BaseModel):
    collection: str = Field(description="The collection to search for the query.")


class RAGResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the LLM.")
    sources: list[str] = Field(description="List of source document identifiers.")
    # log: Optional[str] = Field(description="Reasoning behinde llm's response.")
