from pydantic import BaseModel, Field


class AgentResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the LLM.")
    sources: list[str] = Field(description="List of source document identifiers.")
    tools_used: list[str] = Field(
        description="List of tool names used to generate the answer."
    )
