name: FastAPI Test

on:
  push:
    branches: [ "master", "feat/backend" ]
  pull_request:
    branches: [ "master", "feat/backend" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python with uv and enable cache
      uses: astral-sh/setup-uv@v6
      with:
        python-version-file: "backend/pyproject.toml"
        enable-cache: true
      
    - name: Install the project
      run: uv sync --locked --all-extras --dev
      working-directory: backend

    - name: Run tests
      env:
        APP_ENV: ci
      run: uv run python -m pytest